export const DEVICE_STALE_CHECK_INTERVAL_MS = 1000;
export const DEVICE_DEFAULT_STALE_DATA_AFTER_MS = 5_000;
export const DEVICE_DEFAULT_UPDATE_TIMEOUT_MS = 5_000;
export const DEVICE_DEFAULT_TELEMETRY_POLL_INTERVAL_MS = 2_000;
