export const SOCKET_DEFAULT_CONNECTION_TIMEOUT_MS = 8000;

export const SOCKET_DEFAULT_RECONNECTION_INITIAL_DELAY_MS = 1000;
export const SOCKET_DEFAULT_RECONNECTION_MAX_DELAY_MS = 15000;
export const SOCKET_DEFAULT_RECONNECTION_BACKOFF_MULTIPLIER = 1.8;

export const SOCKET_CONNECTION_HEARTBEAT_INTERVAL_MS = 2000;
export const SOCKET_CONNECTION_HEARTBEAT_TIMEOUT_MS = 6000;

export const SOCKET_COMMANDS_QUEUE_MAX_SIZE = 100;
